class ResourceNotFoundError(Exception):
    """Excepci贸n lanzada cuando un recurso no se encuentra en la base de datos."""
    def __init__(self, message="Recurso no encontrado"):
        self.message = message
        super().__init__(self.message)

class ValidationError(Exception):
    """Excepci贸n lanzada cuando falla la validaci贸n de datos de entrada."""
    def __init__(self, message="Error de validaci贸n"):
        self.message = message
        super().__init__(self.message)